.catalog:
  name: "Redmine"
  version: "latest"
  description: "Redmine with database"
  questions:
    - variable: http_port
      description: "public port to access the Redmine system"
      label: "http Port"
      required: true
      default: "8080"
      type: "int"
    - variable: db_pass
      description: "MySQL database password"
      label: "db password"
      required: true
      default: "secret"
      type: "string"

redmine:
